const language = {
  srp: ['Serbian', 'српски језик'],
  ron: ['Romanian', 'Română'],
  rum: ['Romanian', 'Română'],
  iii: ['Sichuan Yi, Nuosu', 'ꆈꌠ꒿ Nuosuhxop'],
  tah: ['Tahitian', 'Reo Tahiti'],
  tgl: ['Tagalog', 'Wikang Tagalog'],
  yid: ['Yiddish', 'ייִדיש'],
  aka: ['Akan', 'Akan'],
  msa: ['Malay', 'Bahasa Melayu'],
  may: ['Malay', 'Bahasa Melayu'],
  ara: ['Arabic', 'العربية'],
  nor: ['Norwegian', 'Norsk'],
  oji: ['Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ'],
  ful: ['Fulah', 'Fulfulde'],
  fas: ['Persian', 'فارسی'],
  per: ['Persian', 'فارسی'],
  sqi: ['Albanian', 'Shqip'],
  alb: ['Albanian', 'Shqip'],
  aym: ['Aymara', 'aymar aru'],
  aze: ['Azerbaijani', 'azərbaycan dili'],
  zho: ['Chinese', '中文'],
  chi: ['Chinese', '中文'],
  cre: ['Cree', 'ᓀᐦᐃᔭᐍᐏᐣ'],
  est: ['Estonian', 'eesti'],
  grn: ['Guaraní', "Avañe'ẽ"],
  ipk: ['Inupiaq', 'Iñupiaq'],
  iku: ['Inuktitut', 'ᐃᓄᒃᑎᑐᑦ'],
  kau: ['Kanuri', 'Kanuri'],
  kom: ['Komi', 'коми кыв'],
  kon: ['Kongo', 'Kikongo'],
  kur: ['Kurdish', 'Kurdî'],
  lav: ['Latvian', 'latviešu valoda'],
  mlg: ['Malagasy', 'fiteny malagasy'],
  mon: ['Mongolian', 'Монгол хэл'],
  orm: ['Oromo', 'Afaan Oromoo'],
  pus: ['Pashto', 'پښتو'],
  que: ['Quechua', 'Runa Simi'],
  srd: ['Sardinian', 'sardu'],
  swa: ['Swahili', 'Kiswahili'],
  uzb: ['Uzbek', 'Oʻzbek'],
  zha: ['Zhuang', 'Saɯ cueŋƅ'],
  bis: ['Bislama', 'Bislama'],
  nob: ['Norwegian Bokmål', 'Norsk Bokmål'],
  nno: ['Norwegian Nynorsk', 'Norsk Nynorsk'],
  ind: ['Indonesian', 'Bahasa Indonesia'],
  twi: ['Twi', 'Twi'],
  epo: ['Esperanto', 'Esperanto'],
  ina: ['Interlingua', 'Interlingua'],
  ile: ['Interlingue', 'Interlingue'],
  ido: ['Ido', 'Ido'],
  vol: ['Volapük', 'Volapük'],
  bih: ['Bihari languages', 'भोजपुरी'],
  heb: ['Hebrew (modern)', 'עברית'],
  san: ['Sanskrit', 'संस्कृतम्'],
  chu: ['Church Slavic', 'ѩзыкъ словѣньскъ'],
  pli: ['Pali', 'पाऴि'],
  ave: ['Avestan', 'avesta'],
  lat: ['Latin', 'latine'],
  hye: ['Armenian', 'Հայերեն'],
  arm: ['Armenian', 'Հայերեն'],
  ssw: ['Swati', 'SiSwati'],
  bod: ['Tibetan', 'བོད་ཡིག'],
  tib: ['Tibetan', 'བོད་ཡིག'],
  nbl: ['South Ndebele', 'isiNdebele'],
  slv: ['Slovene', 'Slovenski Jezik'],
  ori: ['Oriya', 'ଓଡ଼ିଆ'],
  nde: ['North Ndebele', 'isiNdebele'],
  nau: ['Nauru', 'Dorerin Naoero'],
  mri: ['Maori', 'te reo Māori'],
  mao: ['Maori', 'te reo Māori'],
  mar: ['Marathi', 'मराठी'],
  lub: ['Luba-Katanga', 'Kiluba'],
  run: ['Rundi', 'Ikirundi'],
  khm: ['Central Khmer', 'ខ្មែរ, ខេមរភាសា'],
  fry: ['Western Frisian', 'Frysk'],
  ben: ['Bengali', 'বাংলা'],
  ava: ['Avaric', 'авар мацӀ'],
  abk: ['Abkhazian', 'аҧсуа бызшәа'],
  aar: ['Afar', 'Afaraf'],
  afr: ['Afrikaans', 'Afrikaans'],
  amh: ['Amharic', 'አማርኛ'],
  arg: ['Aragonese', 'aragonés'],
  asm: ['Assamese', 'অসমীয়া'],
  bam: ['Bambara', 'bamanankan'],
  bak: ['Bashkir', 'башҡорт теле'],
  eus: ['Basque', 'euskara'],
  baq: ['Basque', 'euskara'],
  bel: ['Belarusian', 'беларуская мова'],
  bos: ['Bosnian', 'bosanski jezik'],
  bre: ['Breton', 'brezhoneg'],
  bul: ['Bulgarian', 'български език'],
  mya: ['Burmese', 'ဗမာစာ'],
  bur: ['Burmese', 'ဗမာစာ'],
  cat: ['Catalan', 'català'],
  cha: ['Chamorro', 'Chamoru'],
  che: ['Chechen', 'нохчийн мотт'],
  nya: ['Chichewa', 'chiCheŵa'],
  chv: ['Chuvash', 'чӑваш чӗлхи'],
  cor: ['Cornish', 'Kernewek'],
  cos: ['Corsican', 'corsu'],
  hrv: ['Croatian', 'hrvatski'],
  ces: ['Czech', 'čeština'],
  cze: ['Czech', 'čeština'],
  dan: ['Danish', 'dansk'],
  div: ['Divehi', 'ދިވެހި'],
  nld: ['Dutch', 'Nederlands'],
  dut: ['Dutch', 'Nederlands'],
  dzo: ['Dzongkha', 'རྫོང་ཁ'],
  eng: ['English', 'English'],
  ewe: ['Ewe', 'Eʋegbe'],
  fao: ['Faroese', 'føroyskt'],
  fij: ['Fijian', 'vosa Vakaviti'],
  fin: ['Finnish', 'suomi'],
  fra: ['French', 'français'],
  fre: ['French', 'français'],
  glg: ['Galician', 'Galego'],
  kat: ['Georgian', 'ქართული'],
  geo: ['Georgian', 'ქართული'],
  deu: ['German', 'Deutsch'],
  ger: ['German', 'Deutsch'],
  ell: ['Greek (modern)', 'ελληνικά'],
  gre: ['Greek (modern)', 'ελληνικά'],
  guj: ['Gujarati', 'ગુજરાતી'],
  hat: ['Haitian', 'Kreyòl ayisyen'],
  hau: ['Hausa', '(Hausa) هَوُسَ'],
  her: ['Herero', 'Otjiherero'],
  hin: ['Hindi', 'हिन्दी, हिंदी'],
  hmo: ['Hiri Motu', 'Hiri Motu'],
  hun: ['Hungarian', 'magyar'],
  gle: ['Irish', 'Gaeilge'],
  ibo: ['Igbo', 'Asụsụ Igbo'],
  isl: ['Icelandic', 'Íslenska'],
  ice: ['Icelandic', 'Íslenska'],
  ita: ['Italian', 'Italiano'],
  jpn: ['Japanese', '日本語'],
  jav: ['Javanese', 'ꦧꦱꦗꦮ'],
  kal: ['Kalaallisut', 'kalaallisut'],
  kan: ['Kannada', 'ಕನ್ನಡ'],
  kas: ['Kashmiri', 'कश्मीरी'],
  kaz: ['Kazakh', 'қазақ тілі'],
  kik: ['Kikuyu', 'Gĩkũyũ'],
  kin: ['Kinyarwanda', 'Ikinyarwanda'],
  kir: ['Kirghiz', 'Кыргызча'],
  kor: ['Korean', '한국어'],
  kua: ['Kuanyama, Kwanyama', 'Kuanyama'],
  ltz: ['Luxembourgish', 'Lëtzebuergesch'],
  lug: ['Ganda', 'Luganda'],
  lim: ['Limburgan', 'Limburgs'],
  lin: ['Lingala', 'Lingála'],
  lao: ['Lao', 'ພາສາລາວ'],
  lit: ['Lithuanian', 'lietuvių kalba'],
  glv: ['Manx', 'Gaelg, Gailck'],
  mkd: ['Macedonian', 'македонски јазик'],
  mac: ['Macedonian', 'македонски јазик'],
  mal: ['Malayalam', 'മലയാളം'],
  mlt: ['Maltese', 'Malti'],
  mah: ['Marshallese', 'Kajin M̧ajeļ'],
  nav: ['Navajo', 'Diné bizaad'],
  nep: ['Nepali', 'नेपाली'],
  ndo: ['Ndonga', 'Owambo'],
  oci: ['Occitan', 'occitan'],
  oss: ['Ossetian', 'ирон æвзаг'],
  pan: ['Panjabi', 'ਪੰਜਾਬੀ'],
  pol: ['Polish', 'język polski'],
  por: ['Portuguese', 'Português'],
  roh: ['Romansh', 'Rumantsch Grischun'],
  rus: ['Russian', 'русский'],
  snd: ['Sindhi', 'सिन्धी'],
  sme: ['Northern Sami', 'Davvisámegiella'],
  smo: ['Samoan', "gagana fa'a Samoa"],
  sag: ['Sango', 'yângâ tî sängö'],
  gla: ['Gaelic', 'Gàidhlig'],
  sna: ['Shona', 'chiShona'],
  sin: ['Sinhala', 'සිංහල'],
  slk: ['Slovak', 'Slovenčina'],
  slo: ['Slovak', 'Slovenčina'],
  som: ['Somali', 'Soomaaliga'],
  sot: ['Southern Sotho', 'Sesotho'],
  spa: ['Spanish', 'Español'],
  sun: ['Sundanese', 'Basa Sunda'],
  swe: ['Swedish', 'Svenska'],
  tam: ['Tamil', 'தமிழ்'],
  tel: ['Telugu', 'తెలుగు'],
  tgk: ['Tajik', 'тоҷикӣ'],
  tha: ['Thai', 'ไทย'],
  tir: ['Tigrinya', 'ትግርኛ'],
  tuk: ['Turkmen', 'Türkmen'],
  tsn: ['Tswana', 'Setswana'],
  ton: ['Tongan (Tonga Islands)', 'Faka Tonga'],
  tur: ['Turkish', 'Türkçe'],
  tso: ['Tsonga', 'Xitsonga'],
  tat: ['Tatar', 'татар теле'],
  uig: ['Uighur', 'ئۇيغۇرچە'],
  ukr: ['Ukrainian', 'Українська'],
  urd: ['Urdu', 'اردو'],
  ven: ['Venda', 'Tshivenḓa'],
  vie: ['Vietnamese', 'Tiếng Việt'],
  wln: ['Walloon', 'Walon'],
  cym: ['Welsh', 'Cymraeg'],
  wel: ['Welsh', 'Cymraeg'],
  wol: ['Wolof', 'Wollof'],
  xho: ['Xhosa', 'isiXhosa'],
  yor: ['Yoruba', 'Yorùbá'],
  zul: ['Zulu', 'isiZulu'],
  und: ['Undetermined', 'Undetermined'],
}

export default language
