// https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Localization/Ratings/us.csv

const us = {
  G: 'G',
  PG: 'PG',
  'PG-13': 'PG_13',
  R: 'R',
  'NC-17': 'NC_17',

  'TV-Y': 'TV_Y',
  'TV-Y7': 'TV_Y7',
  'TV-Y7-FV': 'TV_Y7_FV',
  'TV-G': 'TV_G',
  'TV-PG': 'TV_PG',
  'TV-PG-D': 'TV_PG_D',
  'TV-PG-L': 'TV_PG_L',
  'TV-PG-S': 'TV_PG_S',
  'TV-PG-V': 'TV_PG_V',
  'TV-PG-DL': 'TV_PG_DL',
  'TV-PG-DS': 'TV_PG_DS',
  'TV-PG-DV': 'TV_PG_DV',
  'TV-PG-LS': 'TV_PG_LS',
  'TV-PG-LV': 'TV_PG_LV',
  'TV-PG-SV': 'TV_PG_SV',
  'TV-PG-DLS': 'TV_PG_DLS',
  'TV-PG-DLV': 'TV_PG_DLV',
  'TV-PG-DSV': 'TV_PG_DSV',
  'TV-PG-LSV': 'TV_PG_LSV',
  'TV-PG-DLSV': 'TV_PG_DLSV',
  'TV-14': 'TV_14',
  'TV-14-D': 'TV_14_D',
  'TV-14-L': 'TV_14_L',
  'TV-14-S': 'TV_14_S',
  'TV-14-V': 'TV_14_V',
  'TV-14-DL': 'TV_14_DL',
  'TV-14-DS': 'TV_14_DS',
  'TV-14-DV': 'TV_14_DV',
  'TV-14-LS': 'TV_14_LS',
  'TV-14-LV': 'TV_14_LV',
  'TV-14-SV': 'TV_14_SV',
  'TV-14-DLS': 'TV_14_DLS',
  'TV-14-DLV': 'TV_14_DLV',
  'TV-14-DSV': 'TV_14_DSV',
  'TV-14-LSV': 'TV_14_LSV',
  'TV-14-DLSV': 'TV_14_DLSV',
  'TV-MA': 'TV_MA',
  'TV-MA-D': 'TV_MA_D',
  'TV-MA-L': 'TV_MA_L',
  'TV-MA-S': 'TV_MA_S',
  'TV-MA-V': 'TV_MA_V',
  'TV-MA-DL': 'TV_MA_DL',
  'TV-MA-DS': 'TV_MA_DS',
  'TV-MA-DV': 'TV_MA_DV',
  'TV-MA-LS': 'TV_MA_LS',
  'TV-MA-LV': 'TV_MA_LV',
  'TV-MA-SV': 'TV_MA_SV',
  'TV-MA-DLS': 'TV_MA_DLS',
  'TV-MA-DLV': 'TV_MA_DLV',
  'TV-MA-DSV': 'TV_MA_DSV',
  'TV-MA-LSV': 'TV_MA_LSV',
  'TV-MA-DLSV': 'TV_MA_DLSV',
}

export default us
