// https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Localization/Ratings/us.csv

const us = {
  G: 'G',
  PG: 'PG',
  'PG-13': 'PG13',
  R: 'R',
  'NC-17': 'NC17',

  'TV-Y': 'TVY',
  'TV-Y7': 'TVY7',
  'TV-Y7-FV': 'TVY7',
  'TV-G': 'TVG',
  'TV-PG': 'TVPG',
  'TV-PG-D': 'TVPGD',
  'TV-PG-L': 'TVPGL',
  'TV-PG-S': 'TVPGS',
  'TV-PG-V': 'TVPGV',
  'TV-PG-DL': 'TVPGDL',
  'TV-PG-DS': 'TVPGDS',
  'TV-PG-DV': 'TVPGDV',
  'TV-PG-LS': 'TVPGLS',
  'TV-PG-LV': 'TVPGLV',
  'TV-PG-SV': 'TVPGSV',
  'TV-PG-DLS': 'TVPGDLS',
  'TV-PG-DLV': 'TVPGDLV',
  'TV-PG-DSV': 'TVPGDSV',
  'TV-PG-LSV': 'TVPGLSV',
  'TV-PG-DLSV': 'TVPGDLSV',
  'TV-14': 'TV14',
  'TV-14-D': 'TV14D',
  'TV-14-L': 'TV14L',
  'TV-14-S': 'TV14S',
  'TV-14-V': 'TV14V',
  'TV-14-DL': 'TV14DL',
  'TV-14-DS': 'TV14DS',
  'TV-14-DV': 'TV14DV',
  'TV-14-LS': 'TV14LS',
  'TV-14-LV': 'TV14LV',
  'TV-14-SV': 'TV14SV',
  'TV-14-DLS': 'TV14DLS',
  'TV-14-DLV': 'TV14DLV',
  'TV-14-DSV': 'TV14DSV',
  'TV-14-LSV': 'TV14LSV',
  'TV-14-DLSV': 'TV14DLSV',
  'TV-MA': 'TVMA',
  'TV-MA-D': 'TVMAD',
  'TV-MA-L': 'TVMAL',
  'TV-MA-S': 'TVMAS',
  'TV-MA-V': 'TVMAV',
  'TV-MA-DL': 'TVMADL',
  'TV-MA-DS': 'TVMADS',
  'TV-MA-DV': 'TVMADV',
  'TV-MA-LS': 'TVMALS',
  'TV-MA-LV': 'TVMALV',
  'TV-MA-SV': 'TVMASV',
  'TV-MA-DLS': 'TVMADLS',
  'TV-MA-DLV': 'TVMADLV',
  'TV-MA-DSV': 'TVMADSV',
  'TV-MA-LSV': 'TVMALSV',
  'TV-MA-DLSV': 'TVMADLSV',
}

export default us
